:tag1: math
:mathjax:

云峰的餐盒饭问题
================

=========================
在云风的blog上看到一个 link:http://blog.codingnow.com/2011/12/probability.html[有趣的概率问题] , 用概率学分析一下这个问题</em>
=========================

== 问题描述 ==
有四份盒饭: 三份牛展, 一份是香菇, 我不知道我的盒饭是什么, 也不知道其他员工的盒饭是什么.
请问:

 * 我的盒饭是牛展的概率是多少
 * 如果员工A的盒饭是牛展, 请问我的盒饭是牛展的概率是多少
 * 如果员工A, B的盒饭都是牛展, 请问我的盒饭是牛展的概率是多少


== 样本空间 ==

分析离散概率问题最好的方法是把样本空间罗列出来:

[options="header"]
|=======================
|事件|我|员工A|员工B|员工C
|$E_1$|香菇|牛展|牛展|牛展
|$E_2$|牛展|香菇|牛展|牛展
|$E_3$|牛展|牛展|香菇|牛展
|$E_4$|牛展|牛展|牛展|香菇
|=======================

这里假设 $ E_1, E_2, E_3, E_4 $ 发生的概率是一样的, 都是1/4

== 事件 ==

通过简单的查表操作就可以得到:

=====================
$ P(I) = E_2∪E_3∪E_4, \\{ I = 我的盒饭是牛展 \\} $
$ P(A) = E_1∪E_3∪E_4, \\{ A = 员工A的盒饭是牛展 \\} $
$ P(B) = E_1∪E_4, \\{ B = 员工A, B的盒饭都是牛展 \\} $
=====================

== 条件概率 ==

条件概率就是事件A在另外一个事件B已经发生条件下的发生概率。条件概率表示为P(A|B)
=====================
latexmath:[$P(A|B) = \frac{P(A \cap B)}{P(B)}$]
=====================

== 计算结果 ==

有了这些知识, 计算开始那三个问题就非常容易了

 * 我的盒饭是牛展的概率是多少
=====================
latexmath:[$P(I) = \frac{E_{2} \bigcup E_{3} \bigcup E_{4}}{U} = \frac{3}{4}$]
=====================

 * 如果员工A的盒饭是牛展, 请问我的盒饭是牛展的概率是多少
=====================
latexmath:[$P(I|A) = \frac{( E_{2} \bigcup E_{3} \bigcup E_{4} ) \bigcap ( E_{1} \bigcup E_{3} \bigcup E_{4} )}{E_{1} \bigcup E_{3} \bigcup E_{4}} = \frac{( E_{3} \bigcup E_{4} )}{E_{1} \bigcup E_{3} \bigcup E_{4}} = \frac{2}{3}$]
=====================

 * 如果员工A, B的盒饭都是牛展, 请问我的盒饭是牛展的概率是多少
=====================
latexmath:[$P(I|B) = \frac{( E_{2} \bigcup E_{3} \bigcup E_{4} ) \bigcap ( E_{1} \bigcup E_{4} )}{E_{1} \bigcup E_{4}} = \frac{E_{4}}{E_{1} \bigcup E_{4}} = \frac{1}{2}$]
=====================
